Add 'collection', 'outputfile' and type to configuration
kb-dk/ds-cumulus-export pull request #11
Opened 2019-10-09 09:24 UTC by danege

2019-10-10 07:10 UTC, tokee requested changes
Technically this worked just as expected. My comments are more about code polishing.

2019-10-10 07:10 UTC, tokee commented on src/main/java/dk/kb/ds/cumulus/export/Configuration.java
> +        this.type = confMap.get(CONF_TYPE);
The `confMap` does not complain about missing values, so running the code without updating the configuration with the new parameters resulted in the generic exception
```
Exception in thread "main" java.lang.NullPointerException
	at dk.kb.ds.cumulus.export.CumulusExport.main(CumulusExport.java:35)
```

Can you add a helper-method ala `this.collection = getObject(confMap, CONF_CUMULUS_COLLECTION)` to `Configuration.java` that throws an exception explaining what key-value pair that was missing, if it is not defined in the configuration?

2019-10-10 07:10 UTC, tokee commented on src/main/java/dk/kb/ds/cumulus/export/CumulusExport.java
> +                String id = "ds_" + collection + "_" + record.getFieldValueOrNull("guid");
This is OK for now, but at some point we'll probably need to do some clean up of the `collection`-part when generating IDs: We don't want spaces, quote signs, colons or other strange characters in IDs.

2019-10-10 07:10 UTC, tokee commented on src/main/java/dk/kb/ds/cumulus/export/CumulusExport.java
> +                String type = Configuration.getType().toString();
`collection` and `type` never changes, so they should be defined outside of the `for (CumulusRecord record : recordCollection) {` loop.

2019-10-10 07:10 UTC, tokee commented on src/main/java/dk/kb/ds/cumulus/export/CumulusExport.java
>              ArgumentCheck.checkNotNull(out, "OutputStream out");
Since we now have custom collections, types etc. we should write a log entry stating what is being processed (no username/passwords in logs!). There should also be a log entry (`DEBUG` level maybe?) for each document produced, with the `id` or possibly other fields we find relevant?

2019-10-11 08:41 UTC, danege commented on src/main/java/dk/kb/ds/cumulus/export/Configuration.java
> +        this.type = confMap.get(CONF_TYPE);
Implemented this

2019-10-11 10:14 UTC, danege commented on src/main/java/dk/kb/ds/cumulus/export/CumulusExport.java
> +                String id = "ds_" + collection + "_" + record.getFieldValueOrNull("guid");
Added check for valid 'type'. Remove special chars in 'collection' if present

2019-10-11 10:14 UTC, danege commented on src/main/java/dk/kb/ds/cumulus/export/CumulusExport.java
> +                String type = Configuration.getType().toString();
Done. Unit test missing for check of  configuration type

2019-10-11 10:14 UTC, danege commented on src/main/java/dk/kb/ds/cumulus/export/CumulusExport.java
>              ArgumentCheck.checkNotNull(out, "OutputStream out");
Log entry for document produced not implemented yet

2019-10-11 11:04 UTC, merged