Modified pom file to create a tar.gz file for deployment
kb-dk/ds-cumulus-export pull request #16
Opened 2019-11-05 12:29 UTC by naderak

2019-11-08 09:16 UTC, danege reviewed
The assembly-plugin is downgraded from 3.1.1 to 2.6, this is why the automatic build fails.
The compiler-plugin is downgraded from 3.8.1 to 3.8.0 and source and target from v 11 to 1.8

2019-11-11 09:25 UTC, tokee requested changes

2019-11-11 09:25 UTC, tokee commented on pom.xml
> +                </plugin>
These are already defined in the parent POM and should not be defined in the project, unless there is a special need. The parent POM can be inspected at https://sbprojects.statsbiblioteket.dk/nexus/service/local/repositories/releases/content/dk/statsbiblioteket/sbprojects/sbprojects-parent/17/sbprojects-parent-17.pom

2019-11-11 09:25 UTC, tokee commented on pom.xml
> +                <artifactId>appassembler-maven-plugin</artifactId>
This is an advanced artifact builder. We'll have to discuss whether we should go this way or stick to the simpler artifact building.

2019-12-20 15:11 UTC, tokee commented
This has been superseded by #28 which packaged the project the same way as the template that is to be used at KB.

2019-12-20 15:12 UTC, closed without merging